spring:
  application:
    name: Expense Tracker

  profiles:
    active: dev

  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

sendgrid:
  api:
    key: test-sendgrid-api-key-for-testing
  from:
    email: noreply@test.com
    name: Expense Tracker

otp:
  expire-in-minute: 3


